
import json
from itertools import chain
from pathlib import Path

with open("build_info.json", "rt") as jf:
    build_info = json.load(jf)


object_files = list(chain.from_iterable([
    Object(source_file) for source_file in build_info["source_files"]
]))

Program(build_info["executable"], build_info["source_files"])

