
import json
from itertools import chain
from pathlib import Path

with open("build_info.json", "rt") as jf:
    build_info = json.load(jf)


object_files = list(chain.from_iterable([
    Object(target=target_obj, source=source_file)
    for target_obj, source_file in build_info["source_files"]
]))

print([(Path(a[0]).name, Path(a[1]).name) for a in build_info["source_files"]])

Program(build_info["executable"], object_files)

