
import json
from pathlib import Path

with open("build_info.json", "rt") as jf:
    build_info = json.load(jf)


object_files = [
    Object(target=Path(source_file).name, source=source_file)
    for source_file in build_info["source_files"]
]

Program(build_info["executable_path"], object_files)

